{% set name = "srt" %}
{% set version = "3.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/srt-{{ version }}.tar.gz
  sha256: 4884315043a4f0740fd1f878ed6caa376ac06d70e135f306a6dc44632eed0cc0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - pip

  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - srt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cdown/srt
  summary: A tiny library for parsing, modifying, and composing SRT files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauranshkumar
